export const CONFIG = {
  PORT: process.env.PORT ? parseInt(process.env.PORT, 10) : 3001,
  GOV_API_BASE_URL: process.env.GOV_API_BASE_URL || 'https://piloto-cbs.tributos.gov.br/servico/calculadora-consumo/api',
  GOV_API_FALLBACK_URL: 'https://piloto-cbs.tributos.gov.br:65519/servico/calculadora-consumo/api',
  CACHE_TTL_SECONDS: 3600, // 1 hour for static tax tables
  REQUEST_TIMEOUT_MS: 8000,
};

// Re-exportações modulares dos catálogos fiscais enriquecidos
export { CLASSIFICACOES_TRIBUTARIAS_DATABASE, obterClassificacaoTributariaUniversal } from './taxClassifications.data.js';
export type { ClassificacaoTributariaItem } from './taxClassifications.data.js';
export { NCM_IS_DATABASE, NCM_GERAIS_DATABASE } from './ncm.data.js';
export type { NcmItem } from './ncm.data.js';

// Linha do tempo oficial da Reforma Tributária (EC 132/2023 e LC 214/2025)
export const TAX_TRANSITION_TIMELINE = [
  {
    ano: 2026,
    fase: 'Período de Teste e Calibração',
    cbsAliquotaPadrao: 0.90, // 0,90% CBS
    ibsUfAliquotaPadrao: 0.10, // 0,10% IBS Estadual
    ibsMunAliquotaPadrao: 0.00, // 0,00% IBS Municipal
    ibsTotalPadrao: 0.10,
    ivaDualTotal: 1.00,
    impostoSeletivoAtivo: false,
    extincaoPisCofins: false,
    extincaoIcmsIss: false,
    redutorCompraGov: 0.0,
    descricao: 'Ano de teste: alíquota piloto de 0,9% CBS e 0,1% IBS compensáveis com PIS/COFINS e ICMS/ISS.',
  },
  {
    ano: 2027,
    fase: 'Entrada Plena da CBS e Imposto Seletivo',
    cbsAliquotaPadrao: 8.40, // alíquota de referência federal
    ibsUfAliquotaPadrao: 0.05,
    ibsMunAliquotaPadrao: 0.05,
    ibsTotalPadrao: 0.10,
    ivaDualTotal: 8.50,
    impostoSeletivoAtivo: true,
    extincaoPisCofins: true, // PIS e COFINS extintos integralmente
    extincaoIcmsIss: false,
    redutorCompraGov: 50.0,
    descricao: 'CBS e Imposto Seletivo entram em vigor integralmente. PIS e COFINS são extintos. Alíquotas de IPI zeradas (exceto ZFM).',
  },
  {
    ano: 2028,
    fase: 'Consolidação da CBS',
    cbsAliquotaPadrao: 8.40,
    ibsUfAliquotaPadrao: 0.05,
    ibsMunAliquotaPadrao: 0.05,
    ibsTotalPadrao: 0.10,
    ivaDualTotal: 8.50,
    impostoSeletivoAtivo: true,
    extincaoPisCofins: true,
    extincaoIcmsIss: false,
    redutorCompraGov: 50.0,
    descricao: 'Manutenção da CBS e início da preparação dos sistemas estaduais e municipais.',
  },
  {
    ano: 2029,
    fase: 'Início da Transição do IBS (10%)',
    cbsAliquotaPadrao: 8.80,
    ibsUfAliquotaPadrao: 0.98,
    ibsMunAliquotaPadrao: 0.78,
    ibsTotalPadrao: 1.76, // 10% do IBS total
    ivaDualTotal: 10.56,
    impostoSeletivoAtivo: true,
    extincaoPisCofins: true,
    extincaoIcmsIss: false,
    reducaoIcmsIssPercentual: 10.0, // Redução de 10% do ICMS e ISS
    redutorCompraGov: 50.0,
    descricao: 'IBS absorve 10% das alíquotas estaduais/municipais; ICMS e ISS são reduzidos em 10%.',
  },
  {
    ano: 2030,
    fase: 'Transição do IBS (20%)',
    cbsAliquotaPadrao: 8.80,
    ibsUfAliquotaPadrao: 1.97,
    ibsMunAliquotaPadrao: 1.57,
    ibsTotalPadrao: 3.54, // 20% do IBS total
    ivaDualTotal: 12.34,
    impostoSeletivoAtivo: true,
    extincaoPisCofins: true,
    extincaoIcmsIss: false,
    reducaoIcmsIssPercentual: 20.0,
    redutorCompraGov: 50.0,
    descricao: 'IBS absorve 20% da arrecadação; ICMS e ISS são reduzidos em 20%.',
  },
  {
    ano: 2031,
    fase: 'Transição do IBS (30%)',
    cbsAliquotaPadrao: 8.80,
    ibsUfAliquotaPadrao: 2.95,
    ibsMunAliquotaPadrao: 2.35,
    ibsTotalPadrao: 5.30, // 30% do IBS total
    ivaDualTotal: 14.10,
    impostoSeletivoAtivo: true,
    extincaoPisCofins: true,
    extincaoIcmsIss: false,
    reducaoIcmsIssPercentual: 30.0,
    redutorCompraGov: 50.0,
    descricao: 'IBS absorve 30%; ICMS e ISS reduzidos em 30%.',
  },
  {
    ano: 2032,
    fase: 'Transição do IBS (40%)',
    cbsAliquotaPadrao: 8.80,
    ibsUfAliquotaPadrao: 3.94,
    ibsMunAliquotaPadrao: 3.14,
    ibsTotalPadrao: 7.08, // 40% do IBS total
    ivaDualTotal: 15.88,
    impostoSeletivoAtivo: true,
    extincaoPisCofins: true,
    extincaoIcmsIss: false,
    reducaoIcmsIssPercentual: 40.0,
    redutorCompraGov: 50.0,
    descricao: 'Último ano de coexistência; ICMS e ISS reduzidos em 40%.',
  },
  {
    ano: 2033,
    fase: 'Vigência Plena do IVA Dual (100%)',
    cbsAliquotaPadrao: 8.80,
    ibsUfAliquotaPadrao: 9.85,
    ibsMunAliquotaPadrao: 7.85,
    ibsTotalPadrao: 17.70,
    ivaDualTotal: 26.50, // Estimativa de referência total (~26,5%)
    impostoSeletivoAtivo: true,
    extincaoPisCofins: true,
    extincaoIcmsIss: true, // ICMS, ISS e IPI totalmente extintos
    redutorCompraGov: 50.0,
    descricao: 'Sistema tributário definitivo: ICMS, ISS, PIS, COFINS e IPI 100% extintos. IBS + CBS em operação plena com arrecadação no destino.',
  },
];

// Situações Tributárias (CST) Oficiais do IBS e CBS (LC 214/2025 e EC 132/2023)
export const CST_CBS_IBS_LIST = [
  {
    codigo: '000',
    nome: 'Tributação Integral (Regime Geral)',
    descricao: 'Operação padrão sujeita às alíquotas de referência da CBS e do IBS.',
    cClassTribDefault: '000001',
    categoria: 'Padrão / Geral',
    fatorReducao: 1.0,
    reducaoPercentual: 0,
    baseLegal: 'Art. 12 da LC 214/2025',
    icon: '🔵',
    aplicavelA: 'Operações em geral com mercadorias e serviços no Regime Geral',
  },
  {
    codigo: '010',
    nome: 'Tributação Monofásica / Alíquotas Uniformes',
    descricao: 'Tributação em etapa única com alíquotas ad rem ou específicas por unidade de medida.',
    cClassTribDefault: '010001',
    categoria: 'Monofásico / Combustíveis',
    fatorReducao: 1.0,
    reducaoPercentual: 0,
    baseLegal: 'Art. 165 a 179 da LC 214/2025',
    icon: '⛽',
    aplicavelA: 'Gasolina, óleo diesel, GLP e combustíveis fósseis',
  },
  {
    codigo: '011',
    nome: 'Alíquotas Uniformes Reduzidas / Biocombustíveis',
    descricao: 'Tributação monofásica com tratamento diferenciado e alíquotas reduzidas para biocombustíveis.',
    cClassTribDefault: '011001',
    categoria: 'Monofásico / Biocombustíveis',
    fatorReducao: 0.5,
    reducaoPercentual: 50,
    baseLegal: 'Art. 175 da LC 214/2025',
    icon: '📉',
    aplicavelA: 'Etanol hidratado combustível, biometano e biodiesel',
  },
  {
    codigo: '200',
    nome: 'Alíquota Reduzida em 60%',
    descricao: 'Redução de 60% nas alíquotas da CBS e do IBS (fator 0,40) para setores essenciais.',
    cClassTribDefault: '200001',
    categoria: 'Redução de Alíquota (-60%)',
    fatorReducao: 0.40,
    reducaoPercentual: 60,
    baseLegal: 'Art. 138 a 141 da LC 214/2025',
    icon: '💊',
    aplicavelA: 'Serviços de educação, saúde, medicamentos, dispositivos médicos, produtos agropecuários e culturais',
  },
  {
    codigo: '210',
    nome: 'Alíquota Reduzida em 30% (Profissões Regulamentadas)',
    descricao: 'Redução de 30% nas alíquotas da CBS e do IBS (fator 0,70) para prestadores intelectuais.',
    cClassTribDefault: '210001',
    categoria: 'Redução de Alíquota (-30%)',
    fatorReducao: 0.70,
    reducaoPercentual: 30,
    baseLegal: 'Art. 142 e 143 da LC 214/2025',
    icon: '⚖️',
    aplicavelA: 'Médicos, advogados, engenheiros, contadores, arquitetos e profissionais regulamentados',
  },
  {
    codigo: '220',
    nome: 'Alíquota Reduzida de 100% (Alíquota Zero / Cesta Básica)',
    descricao: 'Redução de 100% das alíquotas (alíquota zero) com manutenção de créditos na cadeia.',
    cClassTribDefault: '220001',
    categoria: 'Alíquota Zero (-100%)',
    fatorReducao: 0.0,
    reducaoPercentual: 100,
    baseLegal: 'Art. 128 a 130 da LC 214/2025',
    icon: '🛒',
    aplicavelA: 'Itens da Cesta Básica Nacional de Alimentos e medicamentos para doenças graves',
  },
  {
    codigo: '300',
    nome: 'Regimes Específicos de Tributação',
    descricao: 'Operações com regras diferenciadas de base de cálculo, margem de valor agregado ou apuração cumulativa.',
    cClassTribDefault: '300001',
    categoria: 'Regimes Específicos',
    fatorReducao: 1.0,
    reducaoPercentual: 0,
    baseLegal: 'Art. 180 a 270 da LC 214/2025',
    icon: '🏛️',
    aplicavelA: 'Serviços financeiros, seguros, operações imobiliárias, hotelaria, planos de saúde e apostas',
  },
  {
    codigo: '400',
    nome: 'Imunidade Constitucional',
    descricao: 'Operações vedadas de incidência por garantia expressa da Constituição Federal.',
    cClassTribDefault: '400001',
    categoria: 'Imunidade / Não Tributado',
    fatorReducao: 0.0,
    reducaoPercentual: 100,
    baseLegal: 'Art. 8º da LC 214/2025 e Art. 156-A CF/88',
    icon: '🛡️',
    aplicavelA: 'Exportações para o exterior, livros, jornais, periódicos, templos religiosos e partidos políticos',
  },
  {
    codigo: '410',
    nome: 'Isenção Legal',
    descricao: 'Desoneração total do tributo estabelecida por expressa disposição da Lei Complementar.',
    cClassTribDefault: '410001',
    categoria: 'Isenção Legal',
    fatorReducao: 0.0,
    reducaoPercentual: 100,
    baseLegal: 'Art. 144 a 149 da LC 214/2025',
    icon: '🟢',
    aplicavelA: 'Transporte público coletivo urbano, serviços postais universais e entidades beneficentes',
  },
  {
    codigo: '510',
    nome: 'Diferimento do Pagamento',
    descricao: 'Transferência da responsabilidade pelo recolhimento do tributo para a etapa posterior da cadeia produtiva.',
    cClassTribDefault: '510001',
    categoria: 'Diferimento',
    fatorReducao: 0.0,
    reducaoPercentual: 0,
    baseLegal: 'Art. 150 a 153 da LC 214/2025',
    icon: '⏳',
    aplicavelA: 'Insumos industriais, sucatas, bens de capital e minerais brutos entre contribuintes',
  },
  {
    codigo: '550',
    nome: 'Suspensão da Exigibilidade',
    descricao: 'Suspensão temporária do fato gerador ou da exigibilidade tributária vinculada a condição resolutória.',
    cClassTribDefault: '550001',
    categoria: 'Suspensão',
    fatorReducao: 0.0,
    reducaoPercentual: 0,
    baseLegal: 'Art. 154 a 158 da LC 214/2025',
    icon: '⏸️',
    aplicavelA: 'Remessa para industrialização, conserto, feiras e regimes aduaneiros (Drawback / Recof)',
  },
  {
    codigo: '620',
    nome: 'Crédito Presumido Regional (ZFM e ALC)',
    descricao: 'Concessão de crédito presumido de IBS e CBS para incentivo ao desenvolvimento da Amazônia Ocidental.',
    cClassTribDefault: '620001',
    categoria: 'Crédito Presumido / ZFM',
    fatorReducao: 1.0,
    reducaoPercentual: 0,
    baseLegal: 'Art. 430 a 455 da LC 214/2025 e Art. 92-B ADCT',
    icon: '🌴',
    aplicavelA: 'Indústrias incentivadas na Zona Franca de Manaus e Áreas de Livre Comércio',
  },
  {
    codigo: '630',
    nome: 'Crédito Presumido de Produtor Rural Não-Contribuinte',
    descricao: 'Apropriação de crédito presumido pelo adquirente de bens produzidos por produtor rural pessoa física.',
    cClassTribDefault: '630001',
    categoria: 'Crédito Presumido / Agro',
    fatorReducao: 1.0,
    reducaoPercentual: 0,
    baseLegal: 'Art. 160 da LC 214/2025',
    icon: '🌾',
    aplicavelA: 'Aquisições agropecuárias de pequenos produtores rurais não optantes pelo regime geral',
  },
  {
    codigo: '700',
    nome: 'Não Incidência',
    descricao: 'Operações que não configuram fato gerador do IBS nem da CBS por natureza jurídica.',
    cClassTribDefault: '700001',
    categoria: 'Não Incidência',
    fatorReducao: 0.0,
    reducaoPercentual: 100,
    baseLegal: 'Art. 7º da LC 214/2025',
    icon: '⚪',
    aplicavelA: 'Locação pura de bens móveis, cessão onerosa de direitos e transferências patrimoniais societárias',
  },
  {
    codigo: '800',
    nome: 'Compra Governamental com Redutor',
    descricao: 'Vendas para a administração pública com aplicação de desconto equivalente aos tributos.',
    cClassTribDefault: '800001',
    categoria: 'Governo / Compras Públicas',
    fatorReducao: 0.50,
    reducaoPercentual: 50,
    baseLegal: 'Art. 162 a 164 da LC 214/2025',
    icon: '🏛️',
    aplicavelA: 'Fornecimento direto de bens e serviços para órgãos da União, Estados e Municípios',
  },
  {
    codigo: '850',
    nome: 'Ajuste de Transferência entre Estabelecimentos',
    descricao: 'Transferência de mercadorias entre matriz e filiais do mesmo titular sem transferência de propriedade.',
    cClassTribDefault: '850001',
    categoria: 'Transferência Interna',
    fatorReducao: 0.0,
    reducaoPercentual: 0,
    baseLegal: 'Art. 14 da LC 214/2025',
    icon: '🔄',
    aplicavelA: 'Transferência interestadual e intermunicipal entre filiais da mesma pessoa jurídica',
  },
  {
    codigo: '900',
    nome: 'Outras Situações Tributárias Específicas',
    descricao: 'Operações com regras residuais ou autorizações expressas em normas complementares.',
    cClassTribDefault: '900001',
    categoria: 'Outros / Especiais',
    fatorReducao: 1.0,
    reducaoPercentual: 0,
    baseLegal: 'LC 214/2025',
    icon: '⚙️',
    aplicavelA: 'Casos residuais e operações especiais de ajuste',
  },
];

// Situações Tributárias (CST) do Imposto Seletivo (IS)
export const CST_IS_LIST = [
  { codigo: '000', descricao: 'Tributado com Imposto Seletivo', cClassTribDefault: '000001', aplicavelA: 'Veículos, cigarros, bebidas alcoólicas, bebidas açucaradas, minérios' },
  { codigo: '100', descricao: 'Imunidade do Imposto Seletivo (Exportação)', cClassTribDefault: '100001', aplicavelA: 'Exportações de bens e serviços ao exterior' },
  { codigo: '200', descricao: 'Não Incidência / Isenção de IS', cClassTribDefault: '200001', aplicavelA: 'Operações com bens não nocivos à saúde ou ao meio ambiente' },
  { codigo: '550', descricao: 'Suspensão de Imposto Seletivo', cClassTribDefault: '550001', aplicavelA: 'Regimes especiais aduaneiros e transferências industriais' },
];

// Lista de UFs do Brasil
export const UFS_BRASIL = [
  { sigla: 'AC', nome: 'Acre', codigo: 12 },
  { sigla: 'AL', nome: 'Alagoas', codigo: 27 },
  { sigla: 'AP', nome: 'Amapá', codigo: 16 },
  { sigla: 'AM', nome: 'Amazonas', codigo: 13 },
  { sigla: 'BA', nome: 'Bahia', codigo: 29 },
  { sigla: 'CE', nome: 'Ceará', codigo: 23 },
  { sigla: 'DF', nome: 'Distrito Federal', codigo: 53 },
  { sigla: 'ES', nome: 'Espírito Santo', codigo: 32 },
  { sigla: 'GO', nome: 'Goiás', codigo: 52 },
  { sigla: 'MA', nome: 'Maranhão', codigo: 21 },
  { sigla: 'MT', nome: 'Mato Grosso', codigo: 51 },
  { sigla: 'MS', nome: 'Mato Grosso do Sul', codigo: 50 },
  { sigla: 'MG', nome: 'Minas Gerais', codigo: 31 },
  { sigla: 'PA', nome: 'Pará', codigo: 15 },
  { sigla: 'PB', nome: 'Paraíba', codigo: 25 },
  { sigla: 'PR', nome: 'Paraná', codigo: 41 },
  { sigla: 'PE', nome: 'Pernambuco', codigo: 26 },
  { sigla: 'PI', nome: 'Piauí', codigo: 22 },
  { sigla: 'RJ', nome: 'Rio de Janeiro', codigo: 33 },
  { sigla: 'RN', nome: 'Rio Grande do Norte', codigo: 24 },
  { sigla: 'RS', nome: 'Rio Grande do Sul', codigo: 43 },
  { sigla: 'RO', nome: 'Rondônia', codigo: 11 },
  { sigla: 'RR', nome: 'Roraima', codigo: 14 },
  { sigla: 'SC', nome: 'Santa Catarina', codigo: 42 },
  { sigla: 'SP', nome: 'São Paulo', codigo: 35 },
  { sigla: 'SE', nome: 'Sergipe', codigo: 28 },
  { sigla: 'TO', nome: 'Tocantins', codigo: 17 },
  { sigla: 'EX', nome: 'Exterior', codigo: 99 },
];

// Capitais e principais municípios para autocompletar instantâneo
export const MUNICIPIOS_DESTAQUE = [
  { codigo: 3550308, nome: 'São Paulo', uf: 'SP' },
  { codigo: 3304557, nome: 'Rio de Janeiro', uf: 'RJ' },
  { codigo: 3106200, nome: 'Belo Horizonte', uf: 'MG' },
  { codigo: 4106902, nome: 'Curitiba', uf: 'PR' },
  { codigo: 4314902, nome: 'Porto Alegre', uf: 'RS' },
  { codigo: 5300108, nome: 'Brasília', uf: 'DF' },
  { codigo: 2927408, nome: 'Salvador', uf: 'BA' },
  { codigo: 2304400, nome: 'Fortaleza', uf: 'CE' },
  { codigo: 2611606, nome: 'Recife', uf: 'PE' },
  { codigo: 1302603, nome: 'Manaus', uf: 'AM' },
  { codigo: 5208707, nome: 'Goiânia', uf: 'GO' },
  { codigo: 3509502, nome: 'Campinas', uf: 'SP' },
  { codigo: 3205309, nome: 'Vitória', uf: 'ES' },
  { codigo: 4205407, nome: 'Florianópolis', uf: 'SC' },
];
